name: projectomega
description: O futuro de o oculto está além da imaginação.

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  permission_handler: ^11.3.1
  image: ^4.3.0
  video_player: ^2.5.1
  file_picker: ^5.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.3.1
  open_file: ^3.2.1
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  flutter_pdfview: ^1.0.3
  provider: ^6.0.0
  intl: ^0.18.1
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/thumbnail.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Verifique se o caminho está correto