name: projectomega
description: O futuro de o oculto está além da imaginação.

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3 # Certifique-se de usar a versão mais recente
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.00
  permission_handler: ^11.3.1
  image: ^4.3.0
  video_player: ^2.5.1 # ou a versão mais recente
  file_picker: ^5.0.0
  path_provider: ^2.0.11
  url_launcher: ^6.3.1
  open_file: ^3.2.1
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  flutter_pdfview: ^1.0.3 # Pacote para visualização de PDF
  provider: ^6.0.0  # Para gerenciamento de estado
  intl: ^0.18.1 # Para formatação de data e hora
  shared_preferences: ^2.0.6 # Para armazenamento local de preferências

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/thumbnail.png # Adicione o caminho para o seu thumbnail aqui

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf  # Certifique-se de que o caminho esteja correto